# Generated by Django 5.2.17 on 2026-10-05 10:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor')], default='AUDITOR', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='ledger.organization')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('ERP', 'ERP Ledger'), ('BANK', 'Bank Statement'), ('GATEWAY', 'Payment Gateway')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_file', models.FileField(upload_to='ledger-sync/batches/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('checksum', models.CharField(max_length=64)),
                ('source_account', models.CharField(default='primary', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('imported_records', models.PositiveIntegerField(default=0)),
                ('duplicate_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ledger.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('BATCH_UPLOADED', 'Batch Uploaded'), ('BATCH_PROCESSING', 'Batch Processing'), ('TRANSACTION_MATCHED', 'Transaction Matched'), ('DISCREPANCY_CREATED', 'Discrepancy Created'), ('DISCREPANCY_RESOLVED', 'Discrepancy Resolved'), ('STATUS_CHANGED', 'Status Changed')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ledger.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('exact_reference_match', models.BooleanField(default=True)),
                ('date_variance_days', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(365)])),
                ('amount_tolerance_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('currency_must_match', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_rules', to='ledger.organization')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('discrepancy_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('rule_snapshot', models.JSONField(default=dict)),
                ('external_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_reconciliation_runs', to='ledger.batch')),
                ('ledger_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_reconciliation_runs', to='ledger.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='ledger.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ledger.reconciliationrule')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('ERP', 'ERP Ledger'), ('BANK', 'Bank Statement'), ('GATEWAY', 'Payment Gateway')], max_length=20)),
                ('source_account', models.CharField(default='primary', max_length=100)),
                ('row_number', models.PositiveIntegerField()),
                ('transaction_reference', models.CharField(max_length=255)),
                ('normalized_reference', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField()),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('UNRECONCILED', 'Unreconciled'), ('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy'), ('IGNORED', 'Ignored')], default='UNRECONCILED', max_length=20)),
                ('source_row_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_score', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('amount_difference', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('date_difference_days', models.IntegerField(default=0)),
                ('matching_reason', models.JSONField(default=dict)),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='ledger.reconciliationrun')),
                ('external_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='external_match', to='ledger.transaction')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_match', to='ledger.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discrepancy_type', models.CharField(choices=[('UNMATCHED_LEDGER', 'Unmatched Ledger'), ('UNMATCHED_EXTERNAL', 'Unmatched External'), ('AMOUNT_VARIANCE', 'Amount Variance'), ('DATE_VARIANCE', 'Date Variance'), ('DUPLICATE_TRANSACTION', 'Duplicate'), ('CURRENCY_MISMATCH', 'Currency Mismatch'), ('AMBIGUOUS_MATCH', 'Ambiguous Match')], max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='OPEN', max_length=20)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('variance_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='ledger.organization')),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='ledger.reconciliationrun')),
                ('primary_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_discrepancies', to='ledger.transaction')),
                ('secondary_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_discrepancies', to='ledger.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BatchRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('IMPORTED', 'Imported'), ('REUSED', 'Repeated source row'), ('INVALID', 'Invalid row')], max_length=10)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='ledger.batch')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_rows', to='ledger.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='batch_org_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'source_type', '-created_at'], name='batch_org_source_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'source_account', 'checksum'), name='unique_uploaded_file_per_org'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'entity_type', 'entity_id', '-created_at'], name='audit_org_entity_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='user_org_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'is_active'], name='user_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrule',
            index=models.Index(fields=['organization', 'is_active', 'priority'], name='rule_org_active_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrule',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_rule_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrule',
            constraint=models.CheckConstraint(condition=models.Q(('amount_tolerance_percent__gte', 0), ('amount_tolerance_percent__lte', 100)), name='valid_rule_amount_tolerance'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrule',
            constraint=models.CheckConstraint(condition=models.Q(('date_variance_days__lte', 365)), name='valid_rule_date_window'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='run_org_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.UniqueConstraint(fields=('organization', 'ledger_batch', 'external_batch'), name='unique_batch_pair_run'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.CheckConstraint(condition=models.Q(('ledger_batch', models.F('external_batch')), _negated=True), name='different_run_batches'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'batch', 'row_number'], name='txn_org_batch_row_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'status', '-timestamp'], name='txn_org_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'source_type', 'normalized_reference', 'timestamp'], name='txn_org_source_ref_time_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'amount', 'currency', 'timestamp'], name='txn_org_amount_currency_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'source_account', 'source_row_hash'), name='unique_source_transaction_per_org_type'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.0000'))), name='transaction_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatch',
            constraint=models.UniqueConstraint(fields=('reconciliation_run', 'ledger_transaction', 'external_transaction'), name='unique_match_per_run'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='disc_org_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['organization', 'discrepancy_type', 'status'], name='disc_org_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='discrepancy',
            constraint=models.UniqueConstraint(fields=('reconciliation_run', 'primary_transaction'), name='one_discrepancy_per_run_primary'),
        ),
        migrations.AddConstraint(
            model_name='batchrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_batch_row'),
        ),
    ]
